"""helix team groups

Revision ID: 0a8222928873
Revises: c8e73849f1c0
Create Date: 2026-10-04 00:32:46.247795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a8222928873'
down_revision: Union[str, Sequence[str], None] = 'c8e73849f1c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helix_group_version',
    sa.Column('capability_id', sa.String(length=64), nullable=False),
    sa.Column('group_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('drafted_by', sa.String(length=64), nullable=False),
    sa.Column('drafted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('capability_id', 'group_id', 'version')
    )
    op.create_index('uq_helix_group_one_active', 'helix_group_version', ['capability_id', 'group_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.add_column('helix_case', sa.Column('team_group', sa.String(length=64), nullable=True))
    op.add_column('helix_case', sa.Column('team_group_version', sa.Integer(), nullable=True))
    op.add_column('helix_case', sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('helix_case', 'manifest')
    op.drop_column('helix_case', 'team_group_version')
    op.drop_column('helix_case', 'team_group')
    op.drop_index('uq_helix_group_one_active', table_name='helix_group_version', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('helix_group_version')
    # ### end Alembic commands ###
