"""helix runs, attempts, documents, chat, retention

Revision ID: 0cc1410a168d
Revises: 0a8222928873
Create Date: 2026-10-04 02:08:06.319489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cc1410a168d'
down_revision: Union[str, Sequence[str], None] = '0a8222928873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helix_document',
    sa.Column('scope', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('scope', 'name')
    )
    op.create_table('helix_retention_event',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=128), nullable=False),
    sa.Column('capability_id', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('purged_by', sa.String(length=64), nullable=False),
    sa.Column('purged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('helix_case_message',
    sa.Column('message_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['helix_case.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('idx_helix_case_message_case', 'helix_case_message', ['case_id', 'created_at'], unique=False)
    op.add_column('helix_case', sa.Column('run_as', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('helix_case', sa.Column('root_case_id', sa.String(length=128), nullable=True))
    op.add_column('helix_case', sa.Column('attempt', sa.Integer(), server_default='1', nullable=False))
    op.add_column('helix_case', sa.Column('rerun_of', sa.String(length=128), nullable=True))
    op.add_column('helix_case', sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('helix_case', sa.Column('legal_hold', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('helix_case', sa.Column('legal_hold_reason', sa.Text(), nullable=True))
    op.add_column('helix_case', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_helix_case_root_case_id'), 'helix_case', ['root_case_id'], unique=False)
    op.add_column('helix_tool_call', sa.Column('idempotency_key', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_helix_tool_call_idempotency_key'), 'helix_tool_call', ['idempotency_key'], unique=False)
    # ### end Alembic commands ###
    # Existing cases: each is attempt 1 of itself, and its data-scope values
    # come from its case key and the scopes of the manifest it ran on.
    op.execute("UPDATE helix_case SET root_case_id = case_id WHERE root_case_id IS NULL")
    op.execute("""
        UPDATE helix_case c SET scope = COALESCE((
            SELECT jsonb_object_agg(s.value #>> '{}', c.case_key -> s.key)
            FROM jsonb_each(COALESCE(c.manifest, (
                SELECT v.manifest FROM helix_capability_version v
                WHERE v.capability_id = c.capability_id AND v.version = c.manifest_version
            )) -> 'case' -> 'scopes') s), '{}'::jsonb)
        WHERE c.scope IS NULL
    """)
    op.create_index('idx_helix_case_scope', 'helix_case', ['scope'], postgresql_using='gin')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_helix_case_scope', table_name='helix_case')
    op.drop_index(op.f('ix_helix_tool_call_idempotency_key'), table_name='helix_tool_call')
    op.drop_column('helix_tool_call', 'idempotency_key')
    op.drop_index(op.f('ix_helix_case_root_case_id'), table_name='helix_case')
    op.drop_column('helix_case', 'updated_at')
    op.drop_column('helix_case', 'legal_hold_reason')
    op.drop_column('helix_case', 'legal_hold')
    op.drop_column('helix_case', 'scope')
    op.drop_column('helix_case', 'rerun_of')
    op.drop_column('helix_case', 'attempt')
    op.drop_column('helix_case', 'root_case_id')
    op.drop_column('helix_case', 'run_as')
    op.drop_index('idx_helix_case_message_case', table_name='helix_case_message')
    op.drop_table('helix_case_message')
    op.drop_table('helix_retention_event')
    op.drop_table('helix_document')
    # ### end Alembic commands ###
