"""helix switches

Revision ID: 25b5b1f7f87a
Revises: 72e9e577606c
Create Date: 2026-10-04 03:13:40.506148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25b5b1f7f87a'
down_revision: Union[str, Sequence[str], None] = '72e9e577606c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helix_switch',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('target', sa.String(length=160), nullable=False),
    sa.Column('off', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('set_by', sa.String(length=64), nullable=False),
    sa.Column('set_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('kind', 'target')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('helix_switch')
    # ### end Alembic commands ###
