"""helix scheduler tick

Revision ID: 418710f5e68d
Revises: a3de91fd3d5f
Create Date: 2026-10-04 03:07:33.428165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '418710f5e68d'
down_revision: Union[str, Sequence[str], None] = 'a3de91fd3d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helix_scheduler_tick',
    sa.Column('minute', sa.String(length=16), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('minute')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('helix_scheduler_tick')
    # ### end Alembic commands ###
