"""helix evidence documents

Revision ID: 72e9e577606c
Revises: 418710f5e68d
Create Date: 2026-10-04 03:09:28.781241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e9e577606c'
down_revision: Union[str, Sequence[str], None] = '418710f5e68d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('helix_document', sa.Column('kind', sa.String(length=16), server_default='report', nullable=False))
    op.add_column('helix_document', sa.Column('case_id', sa.String(length=128), nullable=True))
    op.add_column('helix_document', sa.Column('uploaded_by', sa.String(length=64), nullable=True))
    op.add_column('helix_document', sa.Column('note', sa.Text(), nullable=True))
    op.create_index(op.f('ix_helix_document_case_id'), 'helix_document', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_helix_document_case_id'), table_name='helix_document')
    op.drop_column('helix_document', 'note')
    op.drop_column('helix_document', 'uploaded_by')
    op.drop_column('helix_document', 'case_id')
    op.drop_column('helix_document', 'kind')
    # ### end Alembic commands ###
