"""helix kg versions in the key

Revision ID: 95f0e14e0b70
Revises: 0cc1410a168d
Create Date: 2026-10-04 02:14:16.257161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f0e14e0b70'
down_revision: Union[str, Sequence[str], None] = '0cc1410a168d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # A node or edge version is keyed by when it became valid, so a change
    # closes one version and opens the next instead of updating in place.
    op.drop_constraint('helix_kg_node_pkey', 'helix_kg_node', type_='primary')
    op.create_primary_key('helix_kg_node_pkey', 'helix_kg_node', ['namespace', 'node_id', 'valid_from'])
    op.alter_column('helix_kg_node', 'valid_from', server_default=None)
    op.drop_constraint('helix_kg_edge_pkey', 'helix_kg_edge', type_='primary')
    op.create_primary_key('helix_kg_edge_pkey', 'helix_kg_edge',
                          ['namespace', 'from_id', 'relation', 'to_id', 'valid_from'])
    op.alter_column('helix_kg_edge', 'valid_from', server_default=None)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_helix_kg_edge_from', 'helix_kg_edge', ['namespace', 'from_id', 'relation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column('helix_kg_edge', 'valid_from', server_default=sa.text('now()'))
    op.drop_constraint('helix_kg_edge_pkey', 'helix_kg_edge', type_='primary')
    op.create_primary_key('helix_kg_edge_pkey', 'helix_kg_edge', ['namespace', 'from_id', 'relation', 'to_id'])
    op.alter_column('helix_kg_node', 'valid_from', server_default=sa.text('now()'))
    op.drop_constraint('helix_kg_node_pkey', 'helix_kg_node', type_='primary')
    op.create_primary_key('helix_kg_node_pkey', 'helix_kg_node', ['namespace', 'node_id'])
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_helix_kg_edge_from', table_name='helix_kg_edge')
    # ### end Alembic commands ###
