"""helix platform tables

Revision ID: 9ca2eb769f3e
Revises: a9c4e2f7b1d5
Create Date: 2026-10-03 21:15:20.573244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ca2eb769f3e'
down_revision: Union[str, Sequence[str], None] = 'a9c4e2f7b1d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helix_capability_version',
    sa.Column('capability_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('drafted_by', sa.String(length=64), nullable=False),
    sa.Column('drafted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('capability_id', 'version')
    )
    op.create_index('uq_helix_capability_one_active', 'helix_capability_version', ['capability_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('helix_case',
    sa.Column('case_id', sa.String(length=128), nullable=False),
    sa.Column('capability_id', sa.String(length=64), nullable=False),
    sa.Column('manifest_version', sa.Integer(), nullable=False),
    sa.Column('case_key', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=True),
    sa.Column('draft', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('opened_by', sa.String(length=64), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index('idx_helix_case_cap', 'helix_case', ['capability_id', 'opened_at'], unique=False)
    op.create_table('helix_kg_edge',
    sa.Column('namespace', sa.String(length=64), nullable=False),
    sa.Column('from_id', sa.String(length=256), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.Column('to_id', sa.String(length=256), nullable=False),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('namespace', 'from_id', 'relation', 'to_id')
    )
    op.create_index('idx_helix_kg_edge_to', 'helix_kg_edge', ['namespace', 'to_id', 'relation'], unique=False)
    op.create_table('helix_kg_node',
    sa.Column('namespace', sa.String(length=64), nullable=False),
    sa.Column('node_id', sa.String(length=256), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('namespace', 'node_id')
    )
    op.create_index('idx_helix_kg_node_kind', 'helix_kg_node', ['namespace', 'kind'], unique=False)
    op.create_table('helix_tool_call',
    sa.Column('call_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=128), nullable=True),
    sa.Column('capability_id', sa.String(length=64), nullable=False),
    sa.Column('connector_id', sa.String(length=64), nullable=False),
    sa.Column('tool', sa.String(length=128), nullable=False),
    sa.Column('requested_by', sa.String(length=32), nullable=False),
    sa.Column('caller', sa.String(length=64), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('denied_reason', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_index('idx_helix_tool_call_case', 'helix_tool_call', ['case_id', 'called_at'], unique=False)
    op.create_table('helix_case_item',
    sa.Column('case_id', sa.String(length=128), nullable=False),
    sa.Column('item_id', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['helix_case.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'item_id')
    )
    op.create_table('helix_decision',
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=128), nullable=False),
    sa.Column('group_id', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['helix_case.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('decision_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('helix_proposal_group',
    sa.Column('case_id', sa.String(length=128), nullable=False),
    sa.Column('group_id', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('group_key', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('item_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('finding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['helix_case.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('helix_proposal_group')
    op.drop_table('helix_decision')
    op.drop_table('helix_case_item')
    op.drop_index('idx_helix_tool_call_case', table_name='helix_tool_call')
    op.drop_table('helix_tool_call')
    op.drop_index('idx_helix_kg_node_kind', table_name='helix_kg_node')
    op.drop_table('helix_kg_node')
    op.drop_index('idx_helix_kg_edge_to', table_name='helix_kg_edge')
    op.drop_table('helix_kg_edge')
    op.drop_index('idx_helix_case_cap', table_name='helix_case')
    op.drop_table('helix_case')
    op.drop_index('uq_helix_capability_one_active', table_name='helix_capability_version', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('helix_capability_version')
    # ### end Alembic commands ###
