"""helix notifications

Revision ID: a3de91fd3d5f
Revises: 95f0e14e0b70
Create Date: 2026-10-04 03:04:47.205515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3de91fd3d5f'
down_revision: Union[str, Sequence[str], None] = '95f0e14e0b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helix_notification',
    sa.Column('notification_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=128), nullable=True),
    sa.Column('capability_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('audience_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('audience_users', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index('idx_helix_notification_at', 'helix_notification', ['created_at'], unique=False)
    op.create_table('helix_notification_read',
    sa.Column('notification_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['helix_notification.notification_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('helix_notification_read')
    op.drop_index('idx_helix_notification_at', table_name='helix_notification')
    op.drop_table('helix_notification')
    # ### end Alembic commands ###
