"""helix publish approval

Revision ID: c8e73849f1c0
Revises: 9ca2eb769f3e
Create Date: 2026-10-03 23:39:43.074307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e73849f1c0'
down_revision: Union[str, Sequence[str], None] = '9ca2eb769f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helix_publish_approval',
    sa.Column('case_id', sa.String(length=128), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['helix_case.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('helix_publish_approval')
    # ### end Alembic commands ###
