"""helix review controls tickets delegation deadlines

Revision ID: d224c0604a72
Revises: 7c4875f053e4
Create Date: 2026-10-04 13:51:00.976503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd224c0604a72'
down_revision: Union[str, Sequence[str], None] = '7c4875f053e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helix_delegation',
    sa.Column('delegation_id', sa.String(length=64), nullable=False),
    sa.Column('from_user', sa.String(length=64), nullable=False),
    sa.Column('to_user', sa.String(length=64), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('from_entitlement', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('delegation_id')
    )
    op.create_index(op.f('ix_helix_delegation_from_user'), 'helix_delegation', ['from_user'], unique=False)
    op.create_index(op.f('ix_helix_delegation_to_user'), 'helix_delegation', ['to_user'], unique=False)
    op.create_table('helix_ticket',
    sa.Column('case_id', sa.String(length=128), nullable=False),
    sa.Column('group_id', sa.String(length=128), nullable=False),
    sa.Column('tool', sa.String(length=128), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('raised_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['helix_case.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'group_id')
    )
    op.add_column('helix_case', sa.Column('due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('helix_case', sa.Column('due_notified', sa.String(length=16), nullable=True))
    op.add_column('helix_case', sa.Column('review_ready_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_helix_case_due_at'), 'helix_case', ['due_at'], unique=False)
    op.add_column('helix_decision', sa.Column('confirmed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('helix_decision', sa.Column('on_behalf_of', sa.String(length=64), nullable=True))
    op.add_column('helix_decision', sa.Column('review_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('helix_decision', 'review_seconds')
    op.drop_column('helix_decision', 'on_behalf_of')
    op.drop_column('helix_decision', 'confirmed')
    op.drop_index(op.f('ix_helix_case_due_at'), table_name='helix_case')
    op.drop_column('helix_case', 'review_ready_at')
    op.drop_column('helix_case', 'due_notified')
    op.drop_column('helix_case', 'due_at')
    op.drop_table('helix_ticket')
    op.drop_index(op.f('ix_helix_delegation_to_user'), table_name='helix_delegation')
    op.drop_index(op.f('ix_helix_delegation_from_user'), table_name='helix_delegation')
    op.drop_table('helix_delegation')
    # ### end Alembic commands ###
