"""operational schema

Revision ID: 96ecd3baf0aa
Revises: aa1b933c1055
Create Date: 2026-09-21 23:34:52.373924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96ecd3baf0aa'
down_revision: Union[str, Sequence[str], None] = 'aa1b933c1055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation',
    sa.Column('rec_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('master_book', sa.String(length=64), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('books_total', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('rec_id')
    )
    op.create_index('idx_rec_region', 'reconciliation', ['region', 'scheduled_time'], unique=False)
    op.create_table('run',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('rec_id', sa.String(length=32), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('books_open', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rec_id'], ['reconciliation.rec_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('idx_run_date', 'run', ['business_date', 'rec_id'], unique=False)
    op.create_table('source_call',
    sa.Column('call_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_session_id', sa.String(length=64), nullable=False),
    sa.Column('application_name', sa.String(length=32), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('validated_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=False),
    sa.Column('entitlement_result', sa.String(length=16), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('called_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_session_id'], ['investigation_session.investigation_session_id'], ),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_index('idx_call_session', 'source_call', ['investigation_session_id', 'called_ts'], unique=False)
    op.add_column('break_event', sa.Column('reason_text', sa.Text(), nullable=True))
    op.add_column('break_event', sa.Column('is_ungrounded', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('break_event', sa.Column('first_seen_run_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('break_event', 'first_seen_run_id')
    op.drop_column('break_event', 'is_ungrounded')
    op.drop_column('break_event', 'reason_text')
    op.drop_index('idx_call_session', table_name='source_call')
    op.drop_table('source_call')
    op.drop_index('idx_run_date', table_name='run')
    op.drop_table('run')
    op.drop_index('idx_rec_region', table_name='reconciliation')
    op.drop_table('reconciliation')
    # ### end Alembic commands ###
