"""initial

Revision ID: aa1b933c1055
Revises: 
Create Date: 2026-09-21 20:03:13.218936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa1b933c1055'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('investigation_session',
    sa.Column('investigation_session_id', sa.String(length=64), nullable=False),
    sa.Column('reconciliation_id', sa.String(length=64), nullable=False),
    sa.Column('master_book', sa.String(length=64), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('investigation_session_id')
    )
    op.create_table('node',
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('natural_key', sa.String(length=128), nullable=False),
    sa.Column('legal_entity_id', sa.String(length=64), nullable=False),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('recorded_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recorded_to', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_index('idx_node_entity', 'node', ['legal_entity_id', 'node_type'], unique=False)
    op.create_index('idx_node_type_key', 'node', ['node_type', 'natural_key'], unique=False)
    op.create_table('analysis_version',
    sa.Column('analysis_version_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_session_id', sa.String(length=64), nullable=False),
    sa.Column('supersedes', sa.String(length=64), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_tier', sa.String(length=16), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('skill_version', sa.String(length=32), nullable=False),
    sa.Column('model_identifier', sa.String(length=64), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_session_id'], ['investigation_session.investigation_session_id'], ),
    sa.PrimaryKeyConstraint('analysis_version_id')
    )
    op.create_table('break_event',
    sa.Column('break_id', sa.String(length=64), nullable=False),
    sa.Column('book_id', sa.String(length=64), nullable=False),
    sa.Column('line_code', sa.String(length=32), nullable=False),
    sa.Column('cob_date', sa.Date(), nullable=False),
    sa.Column('fo_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('bo_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('delta', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('pattern_code', sa.String(length=32), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('recorded_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['node.node_id'], ),
    sa.PrimaryKeyConstraint('break_id')
    )
    op.create_index('idx_similar_breaks', 'break_event', ['book_id', 'line_code', 'cob_date'], unique=False)
    op.create_table('edge',
    sa.Column('edge_id', sa.String(length=64), nullable=False),
    sa.Column('from_node_id', sa.String(length=64), nullable=False),
    sa.Column('to_node_id', sa.String(length=64), nullable=False),
    sa.Column('edge_type', sa.String(length=32), nullable=False),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('recorded_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recorded_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_node_id'], ['node.node_id'], ),
    sa.ForeignKeyConstraint(['to_node_id'], ['node.node_id'], ),
    sa.PrimaryKeyConstraint('edge_id')
    )
    op.create_index('idx_edge_from', 'edge', ['from_node_id', 'edge_type', 'valid_from', 'valid_to'], unique=False)
    op.create_index('idx_edge_to', 'edge', ['to_node_id', 'edge_type', 'valid_from', 'valid_to'], unique=False)
    op.create_table('evidence_item',
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_session_id', sa.String(length=64), nullable=False),
    sa.Column('source_application', sa.String(length=32), nullable=False),
    sa.Column('storage_mode', sa.String(length=16), nullable=False),
    sa.Column('reference_uri', sa.Text(), nullable=False),
    sa.Column('integrity_hash', sa.String(length=64), nullable=False),
    sa.Column('is_original_analysis', sa.Boolean(), nullable=False),
    sa.Column('retrieved_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_session_id'], ['investigation_session.investigation_session_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_table('pattern_group',
    sa.Column('group_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_session_id', sa.String(length=64), nullable=False),
    sa.Column('pattern_code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('break_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('historical_approval_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_session_id'], ['investigation_session.investigation_session_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('break_embedding',
    sa.Column('break_id', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('model_identifier', sa.String(length=64), nullable=False),
    sa.Column('embedded_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['break_id'], ['break_event.break_id'], ),
    sa.PrimaryKeyConstraint('break_id')
    )
    op.create_table('controller_decision',
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_session_id', sa.String(length=64), nullable=False),
    sa.Column('group_id', sa.String(length=64), nullable=True),
    sa.Column('controller_user_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('decided_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['pattern_group.group_id'], ),
    sa.ForeignKeyConstraint(['investigation_session_id'], ['investigation_session.investigation_session_id'], ),
    sa.PrimaryKeyConstraint('decision_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_decision_idem', 'controller_decision', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_decision_idem', table_name='controller_decision')
    op.drop_table('controller_decision')
    op.drop_table('break_embedding')
    op.drop_table('pattern_group')
    op.drop_table('evidence_item')
    op.drop_index('idx_edge_to', table_name='edge')
    op.drop_index('idx_edge_from', table_name='edge')
    op.drop_table('edge')
    op.drop_index('idx_similar_breaks', table_name='break_event')
    op.drop_table('break_event')
    op.drop_table('analysis_version')
    op.drop_index('idx_node_type_key', table_name='node')
    op.drop_index('idx_node_entity', table_name='node')
    op.drop_table('node')
    op.drop_table('investigation_session')
    # ### end Alembic commands ###
