/**
 * Generate src/styles/tokens.css from docs/design/mock-tokens.css.
 *
 *   node scripts/build-tokens.mjs
 *
 * The source is extracted verbatim from FoboControlTower (1).html and is
 * read-only. One transformation is applied: the Google Fonts @import is
 * stripped, because this file is inlined into globals.css and an @import
 * must precede every other rule. Fonts are loaded by next/font in
 * src/app/layout.js instead, which self-hosts them.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const SOURCE = resolve(here, '../../../docs/design/mock-tokens.css');
const TARGET = resolve(here, '../src/styles/tokens.css');

const FONT_IMPORT = /^@import url\(['"]https:\/\/fonts\.googleapis\.com[^)]*\);?\s*$/m;

const source = readFileSync(SOURCE, 'utf8');
if (!FONT_IMPORT.test(source)) {
  console.warn('warning: no Google Fonts @import found — has the source changed?');
}

const banner = `/* GENERATED by scripts/build-tokens.mjs from docs/design/mock-tokens.css.
   Do not edit by hand. The Google Fonts @import is stripped here and the
   fonts are loaded by next/font in src/app/layout.js. */\n\n`;

writeFileSync(TARGET, banner + source.replace(FONT_IMPORT, '').trimStart());

const count = (source.match(/^\s*--/gm) ?? []).length;
console.log(`wrote ${TARGET} (${count} tokens)`);
